# Add path to local module
path_utils = workflow.source_path("utils/__init__.py")

sys.path.insert(0, Path(path_utils).parent.as_posix())

from snakemake.utils import min_version
from utils.config import ChandraConfig

# set minimum snakemake version
min_version("6.4.1")

# setup config file
config_obj = ChandraConfig.read("config/config.yaml")

report: "report/workflow.rst"

# load rules
include: "rules/download_chandra_obsid.smk"
include: "rules/chandra_repro.smk"
include: "rules/reproject_events.smk"


obs_ids = [f"{obs_id:05d}" for obs_id in config_obj.obs_ids]

# all rule 
rule all:
    input:
        expand("results/{config_name}/{obs_id}/events/acisf{obs_id}_repro_evt2_reprojected.fits", obs_id=obs_ids, config_name=config_obj.name)