# Conda environment for reducing fermi data
name: snakemake-workflow-chandra

channels:
  - conda-forge
  - bioconda
  - https://cxc.cfa.harvard.edu/conda/ciao
  
variables:
  PYTHONNOUSERSITE: "1"
  
dependencies:
  - python=3.9
  - snakemake>=7.25.1
  - pydantic
  - astropy<6.0
  - gammapy>=1.3
  - regions>=0.5
  - jupyter
  - ciao
  - pyciao
  - ciao-contrib
  - sherpa
