name: (((xsphabs.absgal * powlaw1d.pwlsoft) + (xsphabs.absclstr * powlaw1d.pwlhard))
    + xsgaussian.feka)
type: binaryopmodel
operator: +
lhs:
    name: ((xsphabs.absgal * powlaw1d.pwlsoft) + (xsphabs.absclstr * powlaw1d.pwlhard))
    type: binaryopmodel
    operator: +
    lhs:
        name: (xsphabs.absgal * powlaw1d.pwlsoft)
        type: binaryopmodel
        operator: '*'
        lhs:
            name: xsphabs.absgal
            type: xsphabs
            parameters:
            -   name: nH
                value: 0.305078368455385
                min: 0.0
                max: 1000000.0
                frozen: false
                unit: 10^22 atoms / cm^2
        rhs:
            name: powlaw1d.pwlsoft
            type: powlaw1d
            parameters:
            -   name: gamma
                value: 1.9336420864114412
                min: -10.0
                max: 10.0
                frozen: false
                unit: ''
            -   name: ref
                value: 1.0
                min: -3.4028234663852886e+38
                max: 3.4028234663852886e+38
                frozen: true
                unit: ''
            -   name: ampl
                value: 0.00010156913891017345
                min: 0.0
                max: 3.4028234663852886e+38
                frozen: false
                unit: ''
    rhs:
        name: (xsphabs.absclstr * powlaw1d.pwlhard)
        type: binaryopmodel
        operator: '*'
        lhs:
            name: xsphabs.absclstr
            type: xsphabs
            parameters:
            -   name: nH
                value: 16.10915455537026
                min: 0.0
                max: 1000000.0
                frozen: false
                unit: 10^22 atoms / cm^2
        rhs:
            name: powlaw1d.pwlhard
            type: powlaw1d
            parameters:
            -   name: gamma
                value: 0.6525907313520264
                min: -10.0
                max: 10.0
                frozen: false
                unit: ''
            -   name: ref
                value: 1.0
                min: -3.4028234663852886e+38
                max: 3.4028234663852886e+38
                frozen: true
                unit: ''
            -   name: ampl
                value: 0.0006270997063240765
                min: 0.0
                max: 3.4028234663852886e+38
                frozen: false
                unit: ''
rhs:
    name: xsgaussian.feka
    type: xsgaussian
    parameters:
    -   name: LineE
        value: 6.102066477910042
        min: 0.0
        max: 1000000.0
        frozen: false
        unit: keV
    -   name: Sigma
        value: 0.04981893395162435
        min: 0.0
        max: 20.0
        frozen: false
        unit: keV
    -   name: norm
        value: 1.893923448615761e-05
        min: 0.0
        max: 1.0e+24
        frozen: false
        unit: ''
